-- Create relation table between houses and admin-managed categories

CREATE TABLE IF NOT EXISTS public.house_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  house_id BIGINT NOT NULL REFERENCES public.houses(id) ON DELETE CASCADE,
  category_id BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (house_id, category_id)
);

ALTER TABLE public.house_categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can read house categories" ON public.house_categories;
CREATE POLICY "Admins can read house categories"
ON public.house_categories
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.admin_users au
    WHERE au.auth_user_id = auth.uid()
      AND au.role = 'admin'::user_role
  )
);

DROP POLICY IF EXISTS "Admins can insert house categories" ON public.house_categories;
CREATE POLICY "Admins can insert house categories"
ON public.house_categories
FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.admin_users au
    WHERE au.auth_user_id = auth.uid()
      AND au.role = 'admin'::user_role
  )
);

DROP POLICY IF EXISTS "Admins can delete house categories" ON public.house_categories;
CREATE POLICY "Admins can delete house categories"
ON public.house_categories
FOR DELETE
USING (
  EXISTS (
    SELECT 1
    FROM public.admin_users au
    WHERE au.auth_user_id = auth.uid()
      AND au.role = 'admin'::user_role
  )
);

GRANT SELECT, INSERT, DELETE ON public.house_categories TO authenticated;
