-- Keep admin_users table in sync when admins are added/updated in users table

CREATE OR REPLACE FUNCTION public.sync_admin_users_from_users()
RETURNS trigger AS $$
BEGIN
  -- If user is admin, upsert into admin_users
  IF NEW.role = 'admin'::user_role OR NEW.role_id = 1 THEN
    INSERT INTO public.admin_users (
      auth_user_id,
      role,
      status,
      is_verified,
      verification_document_url,
      first_name,
      last_name,
      display_name,
      avatar_url,
      date_of_birth,
      gender,
      email,
      alternative_email,
      website,
      phone_country_code,
      phone_number,
      phone_verified,
      phone_verification_code,
      address_line_1,
      address_line_2,
      city,
      state,
      postal_code,
      country,
      coordinates,
      nationality,
      currency_preference,
      timezone,
      preferred_language,
      email_notifications,
      sms_notifications,
      marketing_emails,
      stripe_customer_id,
      payment_methods,
      company_name,
      tax_id,
      business_license,
      created_at,
      updated_at,
      last_login_at,
      preferences,
      metadata,
      role_id
    ) VALUES (
      NEW.auth_user_id,
      'admin'::user_role,
      NEW.status,
      NEW.is_verified,
      NEW.verification_document_url,
      NEW.first_name,
      NEW.last_name,
      NEW.display_name,
      NEW.avatar_url,
      NEW.date_of_birth,
      NEW.gender,
      NEW.email,
      NEW.alternative_email,
      NEW.website,
      NEW.phone_country_code,
      NEW.phone_number,
      NEW.phone_verified,
      NEW.phone_verification_code,
      NEW.address_line_1,
      NEW.address_line_2,
      NEW.city,
      NEW.state,
      NEW.postal_code,
      NEW.country,
      NEW.coordinates,
      NEW.nationality,
      NEW.currency_preference,
      NEW.timezone,
      NEW.preferred_language,
      NEW.email_notifications,
      NEW.sms_notifications,
      NEW.marketing_emails,
      NEW.stripe_customer_id,
      NEW.payment_methods,
      NEW.company_name,
      NEW.tax_id,
      NEW.business_license,
      NEW.created_at,
      NEW.updated_at,
      NEW.last_login_at,
      NEW.preferences,
      NEW.metadata,
      1
    )
    ON CONFLICT (auth_user_id) DO UPDATE
    SET
      role = 'admin'::user_role,
      status = EXCLUDED.status,
      is_verified = EXCLUDED.is_verified,
      verification_document_url = EXCLUDED.verification_document_url,
      first_name = EXCLUDED.first_name,
      last_name = EXCLUDED.last_name,
      display_name = EXCLUDED.display_name,
      avatar_url = EXCLUDED.avatar_url,
      date_of_birth = EXCLUDED.date_of_birth,
      gender = EXCLUDED.gender,
      email = EXCLUDED.email,
      alternative_email = EXCLUDED.alternative_email,
      website = EXCLUDED.website,
      phone_country_code = EXCLUDED.phone_country_code,
      phone_number = EXCLUDED.phone_number,
      phone_verified = EXCLUDED.phone_verified,
      phone_verification_code = EXCLUDED.phone_verification_code,
      address_line_1 = EXCLUDED.address_line_1,
      address_line_2 = EXCLUDED.address_line_2,
      city = EXCLUDED.city,
      state = EXCLUDED.state,
      postal_code = EXCLUDED.postal_code,
      country = EXCLUDED.country,
      coordinates = EXCLUDED.coordinates,
      nationality = EXCLUDED.nationality,
      currency_preference = EXCLUDED.currency_preference,
      timezone = EXCLUDED.timezone,
      preferred_language = EXCLUDED.preferred_language,
      email_notifications = EXCLUDED.email_notifications,
      sms_notifications = EXCLUDED.sms_notifications,
      marketing_emails = EXCLUDED.marketing_emails,
      stripe_customer_id = EXCLUDED.stripe_customer_id,
      payment_methods = EXCLUDED.payment_methods,
      company_name = EXCLUDED.company_name,
      tax_id = EXCLUDED.tax_id,
      business_license = EXCLUDED.business_license,
      updated_at = NOW(),
      last_login_at = EXCLUDED.last_login_at,
      preferences = EXCLUDED.preferences,
      metadata = EXCLUDED.metadata,
      role_id = 1;
  ELSE
    -- If user is no longer admin, remove from admin_users
    DELETE FROM public.admin_users WHERE auth_user_id = NEW.auth_user_id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_sync_admin_users_from_users ON public.users;
CREATE TRIGGER trg_sync_admin_users_from_users
AFTER INSERT OR UPDATE ON public.users
FOR EACH ROW
EXECUTE FUNCTION public.sync_admin_users_from_users();

-- Backfill existing admin users
INSERT INTO public.admin_users (
  auth_user_id,
  role,
  status,
  is_verified,
  verification_document_url,
  first_name,
  last_name,
  display_name,
  avatar_url,
  date_of_birth,
  gender,
  email,
  alternative_email,
  website,
  phone_country_code,
  phone_number,
  phone_verified,
  phone_verification_code,
  address_line_1,
  address_line_2,
  city,
  state,
  postal_code,
  country,
  coordinates,
  nationality,
  currency_preference,
  timezone,
  preferred_language,
  email_notifications,
  sms_notifications,
  marketing_emails,
  stripe_customer_id,
  payment_methods,
  company_name,
  tax_id,
  business_license,
  created_at,
  updated_at,
  last_login_at,
  preferences,
  metadata,
  role_id
)
SELECT
  u.auth_user_id,
  'admin'::user_role,
  u.status,
  u.is_verified,
  u.verification_document_url,
  u.first_name,
  u.last_name,
  u.display_name,
  u.avatar_url,
  u.date_of_birth,
  u.gender,
  u.email,
  u.alternative_email,
  u.website,
  u.phone_country_code,
  u.phone_number,
  u.phone_verified,
  u.phone_verification_code,
  u.address_line_1,
  u.address_line_2,
  u.city,
  u.state,
  u.postal_code,
  u.country,
  u.coordinates,
  u.nationality,
  u.currency_preference,
  u.timezone,
  u.preferred_language,
  u.email_notifications,
  u.sms_notifications,
  u.marketing_emails,
  u.stripe_customer_id,
  u.payment_methods,
  u.company_name,
  u.tax_id,
  u.business_license,
  u.created_at,
  u.updated_at,
  u.last_login_at,
  u.preferences,
  u.metadata,
  1
FROM public.users u
WHERE u.role = 'admin'::user_role OR u.role_id = 1
ON CONFLICT (auth_user_id) DO UPDATE
SET
  role = 'admin'::user_role,
  status = EXCLUDED.status,
  is_verified = EXCLUDED.is_verified,
  verification_document_url = EXCLUDED.verification_document_url,
  first_name = EXCLUDED.first_name,
  last_name = EXCLUDED.last_name,
  display_name = EXCLUDED.display_name,
  avatar_url = EXCLUDED.avatar_url,
  date_of_birth = EXCLUDED.date_of_birth,
  gender = EXCLUDED.gender,
  email = EXCLUDED.email,
  alternative_email = EXCLUDED.alternative_email,
  website = EXCLUDED.website,
  phone_country_code = EXCLUDED.phone_country_code,
  phone_number = EXCLUDED.phone_number,
  phone_verified = EXCLUDED.phone_verified,
  phone_verification_code = EXCLUDED.phone_verification_code,
  address_line_1 = EXCLUDED.address_line_1,
  address_line_2 = EXCLUDED.address_line_2,
  city = EXCLUDED.city,
  state = EXCLUDED.state,
  postal_code = EXCLUDED.postal_code,
  country = EXCLUDED.country,
  coordinates = EXCLUDED.coordinates,
  nationality = EXCLUDED.nationality,
  currency_preference = EXCLUDED.currency_preference,
  timezone = EXCLUDED.timezone,
  preferred_language = EXCLUDED.preferred_language,
  email_notifications = EXCLUDED.email_notifications,
  sms_notifications = EXCLUDED.sms_notifications,
  marketing_emails = EXCLUDED.marketing_emails,
  stripe_customer_id = EXCLUDED.stripe_customer_id,
  payment_methods = EXCLUDED.payment_methods,
  company_name = EXCLUDED.company_name,
  tax_id = EXCLUDED.tax_id,
  business_license = EXCLUDED.business_license,
  updated_at = NOW(),
  last_login_at = EXCLUDED.last_login_at,
  preferences = EXCLUDED.preferences,
  metadata = EXCLUDED.metadata,
  role_id = 1;
